name: ci-golang-workflow

on: 
    pull_request:
        branches:
            - develop

jobs:
  check-aplication:
    runs-on: ubuntu-latest
    strategy:
     matrix:
       go-version: [1.22]
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test
      - run: go run math.go