name: ci-golang-workflow

on: 
  pull_request:
    branches:
      - develop

jobs:
  check-aplication:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: echo  ${{ secrets.DOCKERHUB.USERNAME }}
      - run: go test
      - run: go run math.go


       - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB.USERNAME }}
          password: ${{ secrets.DOCKERHUB.PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB.USERNAME }}/golang-docker:latest