name: ci-golang-workflow

on:
  push:
    branches:
      - master
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - run: go test
      - run: go run math.go