name: ci-golang-workflow

on: 
    pull_request:
        branches:
            - develop
strategy:
  matrix:
    go-version: [1.11, 1.16, 1.17, 1.21]
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test
      - run: go run math.go